### ISSUE TITLE
Vuejs.org VuePress Migration Feedback

### ISSUE THREAD

**Issue by bencodezen** [1950Labs/2018OCT_Demo_VueJS#1]
Hello @sxcamacho and other others I might have missed! 

My name is Ben Hong and I'm a Vue.js Community Partner that is currently working with the Vue.js Core Docs Team to help with updating the platform from Hexo to VuePress. During this time, we plan to have a content freeze in order to ensure all of the sites stay in sync with one another.

As maintainers for the Spanish translation site, are there any pain points or concerns that you might have about this migration? We would love to hear from you and make sure your thoughts are taken into consideration before starting work on this.

Looking forward to your response!

P.S. My apologies for creating an issue in this repo. I was unable to create an Issue in the translation repo directly and felt this was the most generic location to do so.

**Comment by leonelmore** [comment]
Hi Ben! My name is Leonel More and I am one of the Montevideo VueJS Meetup Founders & the owner of 1950Labs. Thanks for contacting us regarding this change! 

I just added you to the translation repo as collaborator, and you should be good now to open the Issue there, comment, etc. If you want, I can add you to the Trello & Slack channel too (let me know).

Go ahead and add the Issue directly over the repo so we can open the conversation with the rest of the community. Thanks again for reaching us!

BTW, I think is a great move!

**Comment by bencodezen** [comment]
Thanks for the quick response @leonelmore! I've gone ahead and moved the issue as you requested. See you over there!
